# Generated by Django 3.0.3 on 2020-10-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='login',
            new_name='login_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='role_ID',
            new_name='role_Id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mobileNumber',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='confirmpassword',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='mobilenumber',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(default='', max_length=50),
        ),
    ]
